# Generated by Django 4.0.1 on 2022-02-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Checked'),
        ),
    ]
